# Generated by Django 4.0.3 on 2022-05-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_short', models.CharField(max_length=50)),
                ('expense_value', models.FloatField()),
                ('expense_currency', models.CharField(max_length=1)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
