# Generated by Django 4.0.4 on 2022-06-26 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_traces', '0002_expenses_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_traces.expense_categories'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expense_date',
            field=models.DateField(auto_now=True),
        ),
    ]
